vich_uploader:
    db_driver: orm

    mappings:
        projects:
            uri_prefix: /uploads/images/projects
            upload_destination: '%kernel.project_dir%/public/uploads/images/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
